### ISSUE TITLE
请教：我用yolov5 源码训练的权重在你的程序上报错，然后用你的代码训练 自定义数据集也各种报错，求指点

### ISSUE THREAD

**Issue by xl199113** [davidfrz/yolov5_distance_count#10]
Traceback (most recent call last):
  File "C:\Users\xl\AppData\Roaming\Python\Python38\site-packages\torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\xl\AppData\Roaming\Python\Python38\site-packages\torch\serialization.py", line 853, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'D:\\0000xl\\pyProjects\\distance\\models\\yolo.py'>

**Comment by pyre001** [comment]
是因为新版本v5权重不支持,我正在尝试用以前的yolo仓库

**Comment by pyre001** [comment]
补充,使用yolov5的3.1仓库(必要)训练权重,替换代码中相应位置就可以运行成功
