### ISSUE TITLE
没有加载到数据集

### ISSUE THREAD

**Issue by 459737087** [davidfrz/yolov5_distance_count#4]
Traceback (most recent call last):
  File "video_remain.py", line 79, in <module>
    img = [letterbox(x, new_shape=640, auto=True)[0] for x in imgs]
  File "video_remain.py", line 79, in <listcomp>
    img = [letterbox(x, new_shape=640, auto=True)[0] for x in imgs]
  File "/output/yolov5_distance_count/utils/datasets.py", line 735, in letterbox
    shape = img.shape[:2]  # current shape [height, width]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by 459737087** [comment]
还有一个问题是怎样计算距离的？我没找到相关的代码。
